export enum ErrorCode {
  not_authenticated = 'not_authenticated',
  invalid_token = 'invalid_token',
  user_not_found = 'user_not_found',
  no_token_provided = 'no_token_provided',
  picture_not_set = 'picture_not_set',
  email_in_use = 'email_in_use',
  email_already_confirmed = 'email_already_confirmed',
  token_expired = 'token_expired',
  token_revoked = 'token_revoked',
  strategy_not_configured = 'strategy_not_configured',
  local_auth_disabled = 'local_auth_disabled',
  bad_credentials = 'bad_credentials',
  invalid_username_password = 'invalid_username_password',
  email_not_confirmed = 'email_not_confirmed',
  invalid_params = 'invalid_params',
  unkown_email_template = 'unkown_email_template',
  invalid_query = 'invalid_query',
  format_not_allowed = 'format_not_allowed',
  invalid_body = 'invalid_body',
  resource_not_found = 'resource_not_found',
}
